### PR TITLE
Properly handling empty GPS logs

### PR DESCRIPTION
**Pull request by cr**

### CODE REVIEW

**Comment by EdwardFinegan** [comment]
I'm assuming this issue is related to this, if not let me know and I can provide more details:

```
Traceback (most recent call last):
  File "/.../PythonENV/bin/hxtool", line 10, in <module>
    sys.exit(main())
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/main.py", line 82, in main
    result = hxtool.cli.run(args)
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/cli/base.py", line 99, in run
    result = current_command.run()
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/cli/gpslog.py", line 93, in run
    hx.comm.erase_gps_log()
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/protocol.py", line 446, in erase_gps_log
    raise ProtocolError(f"Unexpected EraseLog acknowledgement from device: {r}")
hxtool.protocol.ProtocolError: Unexpected EraseLog acknowledgement from device: $PMTK011,MTKGPS*08
```

**Comment by cr** [comment]
It's not related to the empty log. Your handset sent an unexpected message, `$PMTK011,MTKGPS`, which I have never seen coming from my HX870. What model are you using?

**Comment by EdwardFinegan** [comment]
I'm using an HX870. When I saw this I had about 15 GPS points in the log. I downloaded them in both JSON and GPX format. I also printed to the screen. Finally I erased the log. I saw that message on the erase. The erase seemed to be successful from what was reported back when I ran the gpsinfo command with no flag.

**Comment by cr** [comment]
Yes, the message came instead of the expected ACK after the EraseLog command. The log was probably erased anyway.

I'll land a hotfix soon, ignoring that particular message that I wouldn't know what to do with anyway.

**Comment by cr** [comment]
What firmware version are you using?

**Comment by EdwardFinegan** [comment]
Version: 2.04

**Comment by cr** [comment]
I'm still on 2.03. That might explain the different EraseLog behavior.

**Comment by cr** [comment]
#26 just landed hxtool v0.3.0a4. Could you check whether it lets you erase the log without error?

**Comment by cr** [comment]
I can't reproduce the behavior even when running firmware 2.04.

**Comment by EdwardFinegan** [comment]
Unfortunately I'm still seeing the issue. I was able to download the data for each log type, then print the data to the screen. That all worked well. I didn't get to load the files into a map app that would display them so I can't speak to the validity of the formatted data. It did look right after a visual spot check. However when I erased the log I got the following error. It did however actually erase data from the device.

(PythonENV) hxtool gpslog -e                                                                                                
2019-07-16 09:02:43 INFO Device on /dev/cu.usbmodem00000000000011 is HX870 in CP mode, firmware version 02.04
2019-07-16 09:02:44 INFO Log size 4kB, 18 waypoints, 0% full
2019-07-16 09:02:44 INFO Erasing GPS log data from device
Traceback (most recent call last):
  File "/.../PythonENV/bin/hxtool", line 10, in <module>
    sys.exit(main())
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/main.py", line 82, in main
    result = hxtool.cli.run(args)
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/cli/base.py", line 99, in run
    result = current_command.run()
  File "/.../PythonENV/lib/python3.7/site-packages/hxtool/cli/gpslog.py", line 92, in run
    hx.comm.erase_gps_log()
  File "/Users/ed/PythonENV/lib/python3.7/site-packages/hxtool/protocol.py", line 455, in erase_gps_log
    raise ProtocolError(f"Unexpected EraseLog acknowledgement from device: {r}")
hxtool.protocol.ProtocolError: Unexpected EraseLog acknowledgement from device: $PMTK010,002*2D

(PythonENV) hxtool --version                                                                                                
hxtool 0.3.0a4

(PythonENV) hxtool gpslog                                                                                                   
2019-07-16 09:03:33 INFO Device on /dev/cu.usbmodem00000000000011 is HX870 in CP mode, firmware version 02.04
2019-07-16 09:03:33 INFO Log size 0kB, 0 waypoints, 0% full`

**Pull request merged**
